
#define UI_ELEMENT_HEIGTH 25.

#define WINDOW_MARGIN 20.
#define SPACE_MARGIN 10.

#define BUTTON_MARGIN 5.
#define SMALL_BUTTON_WIDTH 140.

#define COLUMN0_WIDTH 155.
#define COLUMN1_WIDTH 200.
#define COLUMN2_WIDTH 200.
#define COLUMN2_HALF_WIDTH 95.
#define TAB1 (WINDOW_MARGIN + COLUMN0_WIDTH + SPACE_MARGIN)
#define TAB2 (WINDOW_MARGIN + COLUMN0_WIDTH + COLUMN1_WIDTH + 2 * SPACE_MARGIN)
#define TAB2_1 (WINDOW_MARGIN + COLUMN0_WIDTH + COLUMN1_WIDTH + COLUMN2_HALF_WIDTH + 3 * SPACE_MARGIN)

#define WINDOW_WIDTH (TAB2 + COLUMN2_WIDTH + WINDOW_MARGIN)
#define WINDOW_HEIGTH 800.
#define BUTTON_SPACE_HEIGHT (9 * UI_ELEMENT_HEIGTH + 2 * SPACE_MARGIN)
#define EXPERIMENT_HEIGHT (WINDOW_HEIGTH - BUTTON_SPACE_HEIGHT)
