
#define UI_ELEMENT_HEIGTH 25.

#define WINDOW_WIDTH 615.
#define WINDOW_HEIGTH 800.
#define WINDOW_MARGIN 20.

#define SPACE_MARGIN 10.

#define BUTTON_SPACE_HEIGHT (6 * UI_ELEMENT_HEIGTH + 2 * SPACE_MARGIN)
#define EXPERIMENT_HEIGHT (WINDOW_HEIGTH - BUTTON_SPACE_HEIGHT)

#define BUTTON_MARGIN 5.
#define SMALL_BUTTON_WIDTH 140.
