
#define UI_ELEMENT_HEIGTH 25.
#define UI_ELEMENT_MARGIN 5.

#define WINDOW_MARGIN 20.
#define SPACE_MARGIN_V 10.

#define SMALL_BUTTON_WIDTH (2. * UI_ELEMENT_HEIGTH)
#define MEDIUM_BUTTON_WIDTH (2. * SMALL_BUTTON_WIDTH + 1. * UI_ELEMENT_MARGIN)
#define BUTTON_WIDTH (3. * SMALL_BUTTON_WIDTH + 2. * UI_ELEMENT_MARGIN)

#define COLUMN0_WIDTH BUTTON_WIDTH
#define COLUMN1_WIDTH (4 * SMALL_BUTTON_WIDTH + 3 * UI_ELEMENT_MARGIN)
#define COLUMN2_WIDTH (2 * SMALL_BUTTON_WIDTH + 1 * UI_ELEMENT_MARGIN)
#define TAB1 (WINDOW_MARGIN + COLUMN0_WIDTH + UI_ELEMENT_MARGIN)
#define TAB1_5 (TAB1 + MEDIUM_BUTTON_WIDTH + UI_ELEMENT_MARGIN)
#define TAB2 (TAB1 + COLUMN1_WIDTH + UI_ELEMENT_MARGIN)

#define WINDOW_POS_X 50.
#define WINDOW_POS_Y 50.
#define WINDOW_WIDTH (3. * BUTTON_WIDTH + 2. * UI_ELEMENT_MARGIN + 2. * WINDOW_MARGIN)
#define WINDOW_HEIGTH 600.

#define BUTTON_SPACE_HEIGHT (9 * UI_ELEMENT_HEIGTH + 2 * SPACE_MARGIN_V)
#define EXPERIMENT_HEIGHT (WINDOW_HEIGTH - BUTTON_SPACE_HEIGHT)
