

#include "../NALib/NAFile.h"

void writeNALibTopCopyright(NAFile* file){
  NAUTF8Char str[] = "\n\
// This file is part of NALib, a collection of C and C++ source code \n\
// intended for didactical purposes. Full license notice at the bottom. \n\
\n";
  naWriteFileStringWithFormat(file, str);
}



void writeNALibBottomCopyright(NAFile* file){
  NAUTF8Char str[] = "\n\
// Copyright (c) NALib, Tobias Stamm \n\
// \n\
// Permission is hereby granted, free of charge, to any person obtaining \n\
// a copy of this software and associated documentation files (the \n\
// \"Software\"), to deal in the Software without restriction, including \n\
// without limitation the rights to use, copy, modify, merge, publish, \n\
// distribute, sublicense, and/or sell copies of the Software, and to \n\
// permit persons to whom the Software is furnished to do so, subject to \n\
// the following conditions: \n\
// \n\
// The above copyright notice and this permission notice shall be included \n\
// in all copies or substantial portions of the source-code. \n\
// \n\
// In case the source-code of this software is inaccessible to the end-user, \n\
// the above copyright notice and this permission notice shall be included \n\
// in any source-code which is dependent on this software and is accessible \n\
// to the end-user. \n\
// \n\
// THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, \n\
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF \n\
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. \n\
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY \n\
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, \n\
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE \n\
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. \n";
  naWriteFileStringWithFormat(file, str);
}



void writeNALibHeaderFileHead(NAFile* file, NAUTF8Char* includemacro){
  writeNALibTopCopyright(file);
  NAUTF8Char str[] = "#ifndef %s \n\
#define %s \n\
#ifdef __cplusplus \n\
  extern \"C\"{ \n\
#endif \n\n";
  naWriteFileStringWithFormat(file, str, includemacro, includemacro);
}



void writeNALibFooter(NAFile* file, NAUTF8Char* includemacro){
  NAUTF8Char str[] = "\n\
#ifdef __cplusplus \n\
  } // extern \"C\" \n\
#endif \n\
#endif // %s \n\
 \n";
  naWriteFileStringWithFormat(file, str, includemacro);
  writeNALibBottomCopyright(file);
  posix_memalign();
  sysconf();
}



void createTimeData(){
  NAFile hfile = naOpenFileForWriting("creatoroutput/NATimeData.h", NA_FILE_MODE_DEFAULT);
  writeNALibHeaderFileHead(&hfile, "NA_TIMEDATA_INCLUDED");
  NAFile cfile = naOpenFileForWriting("creatoroutput/NATimeData.c", NA_FILE_MODE_DEFAULT);
  writeNALibTopCopyright(&cfile);

  naWriteFileStringWithFormat(&hfile, "// All data in this file is automatically generated using the tz data.\n\n");
  naWriteFileStringWithFormat(&cfile, "// All data in this file is automatically generated using the tz data.\n\n");

  NAString instr;
  naCreateStringFromFileContents(&instr, "Creator/res/tzdata/tzdata2014e/iso3166.tab", NA_TEXT_ENCODING_UTF_8);

  naWriteFileLineWithFormat(&hfile, "typedef enum{");
  NAInt linenum = 0;
  NAString line;
  naCreateString(&line);
  linenum += naParseStringLine(&instr, &line, NA_TRUE);
  while(!naIsStringEmpty(&line)){
    if(*naGetStringChar(&line, 0) != '#'){
      NAString code2;
      naCreateString(&code2);
      naParseStringToken(&line, &code2);
      naDecoupleString(&code2);
      naDecoupleString(&line);
      printf("%s___%s\n", naGetStringUTF8Pointer(&code2), naGetStringUTF8Pointer(&line));
      naWriteFileLineWithFormat(&hfile, "  NA_COUNTRY_CODE2_%s,", naGetStringUTF8Pointer(&code2));
    }
    linenum += naParseStringLine(&instr, &line, NA_TRUE);
  }
  naWriteFileLineWithFormat(&hfile, "  NA_COUNTRY_CODE_COUNT\n} NACountryCode;\n");
  naWriteFileLineWithFormat(&hfile, "extern NAUTF8Char* na_country_codes2[NA_COUNTRY_CODE_COUNT];");
  naWriteFileLineWithFormat(&hfile, "extern NAUTF8Char* na_country_names_en[NA_COUNTRY_CODE_COUNT];");

  writeNALibFooter(&hfile, "NA_TIMEDATA_INCLUDED");
  writeNALibBottomCopyright(&cfile);
  naCloseFile(&hfile);
  naCloseFile(&cfile);
}


int main(){
  createTimeData();
}
